Update draw-keymaps.yml

diff --git a/.github/workflows/draw-keymaps.yml b/.github/workflows/draw-keymaps.yml
--- a/.github/workflows/draw-keymaps.yml
+++ b/.github/workflows/draw-keymaps.yml
@@ -1,22 +1,40 @@
-# Draw keymap diagrams using keymap-drawer ZMK user config workflow
 name: Draw ZMK keymaps
+
 on:
-  workflow_dispatch:
   push:
-    paths:
-      - 'config/*.keymap'
-      - 'config/includes/*.dtsi'
-      - keymap-drawer/config.yaml
-      - .github/workflows/draw-keymaps.yml
+    branches:
+      - main
+  pull_request:
+    branches:
+      - main
 
 jobs:
   draw:
-    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
-    with:
-      keymap_patterns: 'config/*.keymap'
-      config_path: keymap-drawer/config.yaml
-      output_folder: keymap-drawer
-      install_branch: main
-      amend_commit: true
-      draw_args: "ergonaut_one:'-k corne_rotated -l LAYOUT_split_3x6_3'"
-      json_path: keymap-drawer/layouts
+    runs-on: ubuntu-latest
+
+    permissions:
+      contents: write  # Ensure the token has write permissions
+
+    steps:
+    - uses: actions/checkout@v4
+      with:
+        fetch-depth: 2
+
+    - name: Draw keymaps
+      run: |
+        keymap "${config_arg[@]}" draw "keymap-drawer/$keyboard.yaml" $draw_args >"keymap-drawer/$keyboard.svg" \
+        || {
+          keymap "${config_arg[@]}" parse -z "$keymap_file" $parse_args >"keymap-drawer/$keyboard.yaml"
+          echo "ERROR: parsing or drawing failed for $keyboard!"
+          error_occurred=1
+        }
+        DRAWINGS+=("keymap-drawer/$keyboard.yaml" "keymap-drawer/$keyboard.svg")
+      shell: bash
+
+    - name: Commit and push changes
+      uses: stefanzweifel/git-auto-commit-action@v5
+      with:
+        commit_message: "Update keymap drawings"
+        branch: main
+        commit_options: --no-verify
+        file_pattern: keymap-drawer/*
